# Generated by Django 5.2.10 on 2026-01-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(default='character', max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.game')),
            ],
            options={
                'unique_together': {('game', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('raw_text', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='main.game')),
            ],
            options={
                'unique_together': {('game', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('buff', 'Buff'), ('nerf', 'Nerf'), ('fine', 'Fine'), ('rework', 'Rework')], max_length=10)),
                ('skill_band', models.CharField(blank=True, max_length=30)),
                ('mode', models.CharField(blank=True, max_length=30)),
                ('reason_tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='main.balanceitem')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='main.patch')),
            ],
        ),
    ]
