# Generated by Django 5.2.10 on 2026-01-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='source_slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
