# Generated by Django 5.2.10 on 2026-01-25 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_feedback_user_alter_balanceitem_kind_patchsuggestion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='game',
            name='accent_hex',
            field=models.CharField(default='#6366F1', max_length=7),
        ),
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='game_covers/'),
        ),
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='game_icons/'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='short_name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='game',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='game_images/')),
                ('kind', models.CharField(choices=[('screenshot', 'Screenshot'), ('banner', 'Banner'), ('art', 'Artwork')], default='screenshot', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.game')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
