# Generated by Django 5.2.10 on 2026-01-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_game_options_game_accent_hex_game_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='raw_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
