# Generated by Django 5.2.10 on 2026-02-18 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_patch_raw_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Augment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('tier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('cost', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EntityChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('champion', 'Champion'), ('item', 'Item'), ('trait', 'Trait'), ('augment', 'Augment')], max_length=10)),
                ('snippet', models.TextField()),
                ('size', models.CharField(choices=[('all', 'All'), ('large', 'Large'), ('small', 'Small')], default='all', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatchSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('overview', 'Overview'), ('champions', 'Champions'), ('items', 'Items'), ('traits', 'Traits'), ('augments', 'Augments'), ('other', 'Other')], max_length=20)),
                ('size', models.CharField(choices=[('all', 'All'), ('large', 'Large'), ('small', 'Small')], default='all', max_length=10)),
                ('h2', models.CharField(blank=True, max_length=200)),
                ('h4', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('lines_json', models.JSONField(blank=True, default=list)),
                ('unit_tier', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='balanceitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='balanceitem',
            name='game',
        ),
        migrations.AlterModelOptions(
            name='patch',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='entity_type',
            field=models.CharField(choices=[('champion', 'Champion'), ('item', 'Item'), ('trait', 'Trait'), ('augment', 'Augment')], default='champion'),
        ),
        migrations.AddField(
            model_name='patch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='patch',
            index=models.Index(fields=['game', 'version'], name='main_patch_game_id_cc4283_idx'),
        ),
        migrations.AddField(
            model_name='augment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='augments', to='main.game'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='augment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.augment'),
        ),
        migrations.AddField(
            model_name='champion',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champions', to='main.game'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.champion'),
        ),
        migrations.AddField(
            model_name='entitychange',
            name='augment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.augment'),
        ),
        migrations.AddField(
            model_name='entitychange',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.champion'),
        ),
        migrations.AddField(
            model_name='entitychange',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_changes', to='main.patch'),
        ),
        migrations.AddField(
            model_name='item',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.game'),
        ),
        migrations.AddField(
            model_name='entitychange',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
        migrations.AddField(
            model_name='patchsection',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.patch'),
        ),
        migrations.AddField(
            model_name='entitychange',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_changes', to='main.patchsection'),
        ),
        migrations.AddField(
            model_name='trait',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='main.game'),
        ),
        migrations.AddField(
            model_name='entitychange',
            name='trait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.trait'),
        ),
        migrations.AddField(
            model_name='champion',
            name='traits',
            field=models.ManyToManyField(blank=True, related_name='champions', to='main.trait'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='trait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.trait'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['patch', 'entity_type'], name='main_feedba_patch_i_1a4519_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('champion__isnull', False), ('item__isnull', True), ('trait__isnull', True), ('augment__isnull', True)), models.Q(('champion__isnull', True), ('item__isnull', False), ('trait__isnull', True), ('augment__isnull', True)), models.Q(('champion__isnull', True), ('item__isnull', True), ('trait__isnull', False), ('augment__isnull', True)), models.Q(('champion__isnull', True), ('item__isnull', True), ('trait__isnull', True), ('augment__isnull', False)), _connector='OR'), name='feedback_exactly_one_fk'),
        ),
        migrations.AddConstraint(
            model_name='augment',
            constraint=models.UniqueConstraint(fields=('game', 'slug'), name='uniq_augment_game_slug'),
        ),
        migrations.AddConstraint(
            model_name='augment',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='uniq_augment_game_name'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('game', 'slug'), name='uniq_item_game_slug'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='uniq_item_game_name'),
        ),
        migrations.DeleteModel(
            name='BalanceItem',
        ),
        migrations.AddIndex(
            model_name='patchsection',
            index=models.Index(fields=['patch', 'category', 'size'], name='main_patchs_patch_i_26b192_idx'),
        ),
        migrations.AddConstraint(
            model_name='trait',
            constraint=models.UniqueConstraint(fields=('game', 'slug'), name='uniq_trait_game_slug'),
        ),
        migrations.AddConstraint(
            model_name='trait',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='uniq_trait_game_name'),
        ),
        migrations.AddIndex(
            model_name='entitychange',
            index=models.Index(fields=['entity_type', 'patch'], name='main_entity_entity__54a5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='entitychange',
            index=models.Index(fields=['patch', 'size'], name='main_entity_patch_i_ecc2b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitychange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('champion__isnull', False), ('item__isnull', True), ('trait__isnull', True), ('augment__isnull', True)), models.Q(('champion__isnull', True), ('item__isnull', False), ('trait__isnull', True), ('augment__isnull', True)), models.Q(('champion__isnull', True), ('item__isnull', True), ('trait__isnull', False), ('augment__isnull', True)), models.Q(('champion__isnull', True), ('item__isnull', True), ('trait__isnull', True), ('augment__isnull', False)), _connector='OR'), name='entitychange_exactly_one_fk'),
        ),
        migrations.AddConstraint(
            model_name='champion',
            constraint=models.UniqueConstraint(fields=('game', 'slug'), name='uniq_champion_game_slug'),
        ),
        migrations.AddConstraint(
            model_name='champion',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='uniq_champion_game_name'),
        ),
    ]
