# Generated by Django 5.2.10 on 2026-02-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_augment_champion_entitychange_item_patchsection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='augment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trait',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='augment',
            name='uniq_augment_game_slug',
        ),
        migrations.RemoveConstraint(
            model_name='augment',
            name='uniq_augment_game_name',
        ),
        migrations.RemoveConstraint(
            model_name='trait',
            name='uniq_trait_game_slug',
        ),
        migrations.RemoveConstraint(
            model_name='trait',
            name='uniq_trait_game_name',
        ),
        migrations.AddField(
            model_name='augment',
            name='ddragon_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='augment',
            name='ddragon_image_full',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='augment',
            name='ddragon_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='augment',
            name='set_key',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='trait',
            name='ddragon_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trait',
            name='ddragon_image_full',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trait',
            name='ddragon_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trait',
            name='set_key',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddConstraint(
            model_name='augment',
            constraint=models.UniqueConstraint(fields=('game', 'set_key', 'slug'), name='uniq_augment_game_set_slug'),
        ),
        migrations.AddConstraint(
            model_name='trait',
            constraint=models.UniqueConstraint(fields=('game', 'set_key', 'slug'), name='uniq_trait_game_set_slug'),
        ),
    ]
