# Generated by Django 5.2.10 on 2026-02-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_augment_options_alter_trait_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='champion',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='champion',
            name='uniq_champion_game_slug',
        ),
        migrations.RemoveConstraint(
            model_name='champion',
            name='uniq_champion_game_name',
        ),
        migrations.AddField(
            model_name='champion',
            name='ddragon_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='champion',
            name='ddragon_image_full',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='champion',
            name='ddragon_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='champion',
            name='set_key',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='ddragon_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='ddragon_image_full',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='ddragon_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='set_key',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddConstraint(
            model_name='champion',
            constraint=models.UniqueConstraint(fields=('game', 'set_key', 'slug'), name='uniq_champion_game_set_slug'),
        ),
    ]
