# Generated by Django 5.2.10 on 2026-02-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_champion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='uniq_item_game_slug',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='uniq_item_game_name',
        ),
        migrations.AddField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('core', 'Core'), ('radiant', 'Radiant'), ('artifact', 'Artifact'), ('set', 'Set-specific')], db_index=True, default='core', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='subgroup',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('game', 'set_key', 'kind', 'slug'), name='uniq_item_game_set_kind_slug'),
        ),
    ]
